SERVICE_KEYWORDS = {
    "instagram.com": "Instagram", "mail.instagram.com": "Instagram",
    "facebook.com": "Facebook", "facebookmail.com": "Facebook",
    "twitter.com": "Twitter", "x.com": "Twitter",
    "tiktok.com": "TikTok", "snapchat.com": "Snapchat",
    "discord.com": "Discord", "telegram.org": "Telegram",
    "reddit.com": "Reddit", "linkedin.com": "LinkedIn",
    "twitch.tv": "Twitch", "onlyfans.com": "OnlyFans",
    "patreon.com": "Patreon", "vk.com": "VK",
    "whatsapp.com": "WhatsApp", "youtube.com": "YouTube",
    "netflix.com": "Netflix", "info@netflix.com": "Netflix",
    "spotify.com": "Spotify", "disneyplus.com": "Disney+",
    "hulu.com": "Hulu", "hbo.com": "HBO",
    "amazon.com": "Amazon", "primevideo.com": "Prime Video",
    "apple.com": "Apple", "peacocktv.com": "Peacock",
    "paramountplus.com": "Paramount+", "tidal.com": "Tidal",
    "deezer.com": "Deezer", "xbox.com": "Xbox",
    "playstation.com": "PlayStation", "nintendo.com": "Nintendo",
    "steampowered.com": "Steam", "epicgames.com": "Epic Games",
    "riotgames.com": "Riot Games", "minecraft.net": "Minecraft",
    "roblox.com": "Roblox", "ubisoft.com": "Ubisoft",
    "ea.com": "EA", "blizzard.com": "Blizzard",
    "valorant.com": "Valorant", "fortnite.com": "Fortnite",
    "pubg.com": "PUBG", "callofduty.com": "COD",
    "rockstargames.com": "Rockstar", "paypal.com": "PayPal",
    "venmo.com": "Venmo", "cash.app": "CashApp",
    "stripe.com": "Stripe", "revolut.com": "Revolut",
    "wise.com": "Wise", "coinbase.com": "Coinbase",
    "binance.com": "Binance", "kraken.com": "Kraken",
    "robinhood.com": "Robinhood", "ebay.com": "eBay",
    "aliexpress.com": "AliExpress", "etsy.com": "Etsy",
    "walmart.com": "Walmart", "target.com": "Target",
    "shopify.com": "Shopify", "nike.com": "Nike",
    "adidas.com": "Adidas", "ubereats.com": "UberEats",
    "doordash.com": "DoorDash", "grubhub.com": "GrubHub",
    "deliveroo.co.uk": "Deliveroo", "uber.com": "Uber",
    "lyft.com": "Lyft", "airbnb.com": "Airbnb",
    "booking.com": "Booking.com", "expedia.com": "Expedia",
    "dropbox.com": "Dropbox", "google.com": "Google Drive",
    "onedrive.com": "OneDrive", "icloud.com": "iCloud",
    "nordvpn.com": "NordVPN", "expressvpn.com": "ExpressVPN",
    "surfshark.com": "Surfshark", "protonvpn.com": "ProtonVPN",
    "coursera.org": "Coursera", "udemy.com": "Udemy",
    "duolingo.com": "Duolingo", "grammarly.com": "Grammarly",
    "office365.com": "Office 365", "zoom.us": "Zoom",
    "slack.com": "Slack", "adobe.com": "Adobe",
    "canva.com": "Canva"
}
